// Dumps the client's static building colliders into shared/walls.ts so the server can check line of sight for shots.
// Uses medium quality (filler buildings differ by quality level) and keeps only solid boxes ≥ 2.5 m on a side.
import fs from 'node:fs';
import { launch, player, ev, adminPassword } from './e2e-lib.js';
const b = await launch();
const A = await player(b, 'bestx', { quality: 'medium', login: true, password: adminPassword(), ambient: false });
const boxes = await ev<{ minX: number; maxX: number; minZ: number; maxZ: number }[]>(A.page, 'window.__beninlife.world.colliders.map(c => ({ minX: c.minX, maxX: c.maxX, minZ: c.minZ, maxZ: c.maxZ }))');
await b.close();
const keep = boxes.filter((c) => Math.max(c.maxX - c.minX, c.maxZ - c.minZ) >= 2.5 && Math.min(c.maxX - c.minX, c.maxZ - c.minZ) >= 0.15);
const r = (n: number) => Math.round(n * 100) / 100;
const flat = keep.flatMap((c) => [r(c.minX), r(c.maxX), r(c.minZ), r(c.maxZ)]);
const lines: string[] = [];
for (let i = 0; i < flat.length; i += 16) lines.push('  ' + flat.slice(i, i + 16).join(', ') + ',');
fs.writeFileSync('shared/walls.ts', `// GENERATED by scripts/gen-walls.ts from the client world colliders (${keep.length} of ${boxes.length} boxes).\n// Flat [minX, maxX, minZ, maxZ, ...] — used by the server for shot line-of-sight checks. Re-run after changing world layout.\nexport const WALLS: number[] = [\n${lines.join('\n')}\n];\n`);
console.log(`walls: kept ${keep.length} of ${boxes.length}`);
